package com.eucappelli.utils;

public class Strings {
    public static final String GREETINGS = "Olá! Eu sou o BOT de Comissão de Estágio da UFRJ!\nIrei te fazer perguntas e " +
            "você irá me fornecer as respostas, não responda nada além das respostas corretas para não atrasar o processo, ok? " +
            "É possível editar suas informações no final, mas vamos agilizar!";
    public static final String INSERT_FULL_NAME = "Me diga seu nome completo!";
    public static final String INVALID_NAME = "Informe um nome válido";
    public static final String DRE_INFORM = "Ok, %s! Agora me informe seu DRE!";
    public static final String RENEWAL_QUESTION = "Seu pedido é uma renovação de estágio?";
    public static final String INVALID_DRE = "Informe um DRE válido!";
    public static final String ADDED_DRE = "DRE %s adicionado ao cadastro!";
    public static final String NO = "Não";
    public static final String YES = "Sim";
    public static final String SELECTED_OPTION = "Você selecionou: %s!";
    public static final String CRA_QUESTION = "Qual é o seu CRA (CR acumulado) atual?";
    public static final String INVALID_CRA = "Informe um CRA válido (exemplo: 6.2)";
    public static final String LEFT_TO_COMPLETE_QUESTION = "Quantas disciplinas faltam para concluir todas as disciplinas até o 4º período? Responda 0 caso já tenha concluído todas";
    public static final String FILE_QUESTION = "Por favor, envie o seu %s atualizado";
    public static final String INVALID_FILE = "Envie um arquivo PDF válido";
    public static final String SUCCESS_FILE = "Arquivo adicionado com sucesso";
    public static final String INFO_HEADER = "Essas foram as informações inseridas no seu cadastro:";
    public static final String FULL_NAME = "Nome completo";
    public static final String DRE = "DRE";
    public static final String RENEWAL = "Pedido de renovação?";
    public static final String CRA = "CRA";
    public static final String LEFT_TO_COMPLETE = "Disciplinas faltantes até o 4º período";
    public static final String BOA = "BOA";
    public static final String BOLETIM = "Boletim";
    public static final String CONFIRMATION_QUESTION = "Se precisar editar alguma informação, escolha uma opção abaixo. Caso não precise, escolha 'Nenhum'";
    public static final String SEND_QUESTION = "Se precisa editar alguma informação, escolha uma opção abaixo. Caso não precise, escolha 'Enviar' para enviar seu pedido";
    public static final String COMPANY_NAME_QUESTION = "Nome da Empresa onde fará estágio";
    public static final String COMPANY_EMAIL_QUESTION = "Email de contato da empresa (pode ser do supervisor ou do RH)";
    public static final String INVALID_EMAIL = "Insira um email válido";
    public static final String DRAWN_BY_QUESTION = "O contrato foi elaborado";
    public static final String START_DATE = "Data do início do contrato";
    public static final String END_DATE = "Data do fim do contrato";
    public static final String INVALID_DATE = "Insira uma data válida (formato: dd/MM/yyyy, ex: 30/11/2024)";
    public static final String CONTRACT_FILE_QUESTION = "Envie seu contrato de estágio assinado em PDF";
    public static final String COMPANY_NAME = "Nome da empresa";
    public static final String EMAIL = "Email de contato da empresa";
    public static final String DRAWN_BY = "Elaboração do contrato";
    public static final String CONTRACT = "Contrato de estágio";
    public static final String COMPANY = "Pela própria empresa";
    public static final String AGENCY = "Por um agente de integração (MUDES, CIEE, NUBES, etc.)";
    public static final String UNKNOWN = "Não sei dizer";
    public static final String NONE = "Nenhum";
    public static final String SEND = "Enviar";
    public static final String STATUS_TEXT = "Para ver o status do seu pedido atual só escrever a qualquer momento o comando /status";
    public static final String INFO_TEXT = "Para ver as informações enviadas para a comissão, digite /allinfo\nNão é possível visualizar os arquivos que foram enviados";
    public static final String EDIT_INFO_TEXT = "Para editar suas informações de cadastro, digite /editinfo";
    public static final String EDIT_CONTRACT_TEXT = "Para editar as informações de contrato de estágio, digite /editcontract";
    public static final String REJECTED_WARNING_TEXT = "Se seu pedido for rejeitado, você receberá uma mensagem minha de aviso com o motivo da recusa.";
    public static final String ACCEPTED_WARNING_TEXT = "Se seu pedido for aprovado, você receberá uma mensagem contendo o contrato de estágio assinado.";
    public static final String STATUS = "Status";
    public static final String SENT_DATE = "Data de envio";
    public static final String LAST_UPDATE = "Última atualização";
    public static final String AUTHORIZED = "Aprovado";
    public static final String DENIED = "Reprovado";
    public static final String SENT = "Enviado";
    public static final String AUTHORIZED_UNDER_CONDITION = "Aprovado condicionalmente";
    public static final String REASON = "Motivo";
    public static final String REQUEST_SENT = "Seu pedido foi enviado para a comissão de estágio com sucesso!";
    public static final String PDF_WARNING = "Você precisa enviar um arquivo no formato PDF";

    public static final String USER_IS_NULL = "User is null";
    public static final String ERROR_WHILE_RECEIVING_UPDATE = "Error while receiving update";
    public static final String ERROR_GETTING_USER = "Error getting user";
    public static final String ERROR_GETTING_REQUEST = "Error getting request";
    public static final String ERROR_WHILE_HANDLING_FILE = "Ocorreu um erro ao processar o arquivo enviado, por favor tente novamente.\nSe o erro continuar, por favor contate a administração.";
}
